/* tslint:disable */
/* eslint-disable */
/**
 * Chat - API
 * Chat - API Description
 *
 * The version of the OpenAPI document: 1.1.60
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChangePasswordDTO
 */
export interface ChangePasswordDTO {
    /**
     * 
     * @type {string}
     * @memberof ChangePasswordDTO
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof ChangePasswordDTO
     */
    passwordConfirm: string;
}

/**
 * Check if a given object implements the ChangePasswordDTO interface.
 */
export function instanceOfChangePasswordDTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "password" in value;
    isInstance = isInstance && "passwordConfirm" in value;

    return isInstance;
}

export function ChangePasswordDTOFromJSON(json: any): ChangePasswordDTO {
    return ChangePasswordDTOFromJSONTyped(json, false);
}

export function ChangePasswordDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChangePasswordDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'password': json['password'],
        'passwordConfirm': json['passwordConfirm'],
    };
}

export function ChangePasswordDTOToJSON(value?: ChangePasswordDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'password': value.password,
        'passwordConfirm': value.passwordConfirm,
    };
}

