/* tslint:disable */
/* eslint-disable */
/**
 * Chat - API
 * Chat - API Description
 *
 * The version of the OpenAPI document: 1.1.52
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateReplyDTO
 */
export interface CreateReplyDTO {
    /**
     * 
     * @type {number}
     * @memberof CreateReplyDTO
     */
    commentId: number;
    /**
     * 
     * @type {string}
     * @memberof CreateReplyDTO
     */
    content: string;
}

/**
 * Check if a given object implements the CreateReplyDTO interface.
 */
export function instanceOfCreateReplyDTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "commentId" in value;
    isInstance = isInstance && "content" in value;

    return isInstance;
}

export function CreateReplyDTOFromJSON(json: any): CreateReplyDTO {
    return CreateReplyDTOFromJSONTyped(json, false);
}

export function CreateReplyDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateReplyDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'commentId': json['commentId'],
        'content': json['content'],
    };
}

export function CreateReplyDTOToJSON(value?: CreateReplyDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'commentId': value.commentId,
        'content': value.content,
    };
}

