/* tslint:disable */
/* eslint-disable */
/**
 * Chat - API
 * Chat - API Description
 *
 * The version of the OpenAPI document: 1.1.52
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateConversationRequestDTO
 */
export interface CreateConversationRequestDTO {
    /**
     * 
     * @type {Array<number>}
     * @memberof CreateConversationRequestDTO
     */
    partnerIds: Array<number>;
}

/**
 * Check if a given object implements the CreateConversationRequestDTO interface.
 */
export function instanceOfCreateConversationRequestDTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "partnerIds" in value;

    return isInstance;
}

export function CreateConversationRequestDTOFromJSON(json: any): CreateConversationRequestDTO {
    return CreateConversationRequestDTOFromJSONTyped(json, false);
}

export function CreateConversationRequestDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateConversationRequestDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'partnerIds': json['partnerIds'],
    };
}

export function CreateConversationRequestDTOToJSON(value?: CreateConversationRequestDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'partnerIds': value.partnerIds,
    };
}

