/* tslint:disable */
/* eslint-disable */
/**
 * Chat - API
 * Chat - API Description
 *
 * The version of the OpenAPI document: 1.1.52
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreatePostDTO
 */
export interface CreatePostDTO {
    /**
     * The content of a post
     * @type {string}
     * @memberof CreatePostDTO
     */
    content: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePostDTO
     */
    contentType: string;
}

/**
 * Check if a given object implements the CreatePostDTO interface.
 */
export function instanceOfCreatePostDTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "content" in value;
    isInstance = isInstance && "contentType" in value;

    return isInstance;
}

export function CreatePostDTOFromJSON(json: any): CreatePostDTO {
    return CreatePostDTOFromJSONTyped(json, false);
}

export function CreatePostDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePostDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'content': json['content'],
        'contentType': json['contentType'],
    };
}

export function CreatePostDTOToJSON(value?: CreatePostDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'content': value.content,
        'contentType': value.contentType,
    };
}

