/* tslint:disable */
/* eslint-disable */
/**
 * Chat - API
 * Chat - API Description
 *
 * The version of the OpenAPI document: 1.1.52
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCommentDTO
 */
export interface CreateCommentDTO {
    /**
     * 
     * @type {number}
     * @memberof CreateCommentDTO
     */
    postId: number;
    /**
     * 
     * @type {string}
     * @memberof CreateCommentDTO
     */
    content: string;
}

/**
 * Check if a given object implements the CreateCommentDTO interface.
 */
export function instanceOfCreateCommentDTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "postId" in value;
    isInstance = isInstance && "content" in value;

    return isInstance;
}

export function CreateCommentDTOFromJSON(json: any): CreateCommentDTO {
    return CreateCommentDTOFromJSONTyped(json, false);
}

export function CreateCommentDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCommentDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'postId': json['postId'],
        'content': json['content'],
    };
}

export function CreateCommentDTOToJSON(value?: CreateCommentDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'postId': value.postId,
        'content': value.content,
    };
}

