/* tslint:disable */
/* eslint-disable */
/**
 * Chat - API
 * Chat - API Description
 *
 * The version of the OpenAPI document: 1.1.52
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteCommentDTO
 */
export interface DeleteCommentDTO {
    /**
     * 
     * @type {number}
     * @memberof DeleteCommentDTO
     */
    commentId: number;
}

/**
 * Check if a given object implements the DeleteCommentDTO interface.
 */
export function instanceOfDeleteCommentDTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "commentId" in value;

    return isInstance;
}

export function DeleteCommentDTOFromJSON(json: any): DeleteCommentDTO {
    return DeleteCommentDTOFromJSONTyped(json, false);
}

export function DeleteCommentDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteCommentDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'commentId': json['commentId'],
    };
}

export function DeleteCommentDTOToJSON(value?: DeleteCommentDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'commentId': value.commentId,
    };
}

