/* tslint:disable */
/* eslint-disable */
/**
 * Chat - API
 * Chat - API Description
 *
 * The version of the OpenAPI document: 1.1.60
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetMessagesDTO
 */
export interface GetMessagesDTO {
    /**
     * 
     * @type {number}
     * @memberof GetMessagesDTO
     */
    conversationId: number;
    /**
     * To reduce the amount of data fetched the client can send the id of the last received message and only get messages that are newer than that
     * @type {number}
     * @memberof GetMessagesDTO
     */
    lastMessage?: number;
}

/**
 * Check if a given object implements the GetMessagesDTO interface.
 */
export function instanceOfGetMessagesDTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "conversationId" in value;

    return isInstance;
}

export function GetMessagesDTOFromJSON(json: any): GetMessagesDTO {
    return GetMessagesDTOFromJSONTyped(json, false);
}

export function GetMessagesDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetMessagesDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'conversationId': json['conversationId'],
        'lastMessage': !exists(json, 'lastMessage') ? undefined : json['lastMessage'],
    };
}

export function GetMessagesDTOToJSON(value?: GetMessagesDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'conversationId': value.conversationId,
        'lastMessage': value.lastMessage,
    };
}

