/* tslint:disable */
/* eslint-disable */
/**
 * Chat - API
 * Chat - API Description
 *
 * The version of the OpenAPI document: 1.1.60
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UserResponseDTO } from './UserResponseDTO';
import {
    UserResponseDTOFromJSON,
    UserResponseDTOFromJSONTyped,
    UserResponseDTOToJSON,
} from './UserResponseDTO';

/**
 * 
 * @export
 * @interface ReplyResponseDTO
 */
export interface ReplyResponseDTO {
    /**
     * 
     * @type {number}
     * @memberof ReplyResponseDTO
     */
    id: number;
    /**
     * 
     * @type {Date}
     * @memberof ReplyResponseDTO
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof ReplyResponseDTO
     */
    updatedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof ReplyResponseDTO
     */
    content: string;
    /**
     * 
     * @type {UserResponseDTO}
     * @memberof ReplyResponseDTO
     */
    author: UserResponseDTO | null;
}

/**
 * Check if a given object implements the ReplyResponseDTO interface.
 */
export function instanceOfReplyResponseDTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "updatedAt" in value;
    isInstance = isInstance && "content" in value;
    isInstance = isInstance && "author" in value;

    return isInstance;
}

export function ReplyResponseDTOFromJSON(json: any): ReplyResponseDTO {
    return ReplyResponseDTOFromJSONTyped(json, false);
}

export function ReplyResponseDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReplyResponseDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
        'content': json['content'],
        'author': UserResponseDTOFromJSON(json['author']),
    };
}

export function ReplyResponseDTOToJSON(value?: ReplyResponseDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'createdAt': (value.createdAt.toISOString()),
        'updatedAt': (value.updatedAt.toISOString()),
        'content': value.content,
        'author': UserResponseDTOToJSON(value.author),
    };
}

