/* tslint:disable */
/* eslint-disable */
/**
 * Chat - API
 * Chat - API Description
 *
 * The version of the OpenAPI document: 1.1.52
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdatePostDTO
 */
export interface UpdatePostDTO {
    /**
     * 
     * @type {number}
     * @memberof UpdatePostDTO
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof UpdatePostDTO
     */
    content: string;
    /**
     * 
     * @type {string}
     * @memberof UpdatePostDTO
     */
    contentType: string;
}

/**
 * Check if a given object implements the UpdatePostDTO interface.
 */
export function instanceOfUpdatePostDTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "content" in value;
    isInstance = isInstance && "contentType" in value;

    return isInstance;
}

export function UpdatePostDTOFromJSON(json: any): UpdatePostDTO {
    return UpdatePostDTOFromJSONTyped(json, false);
}

export function UpdatePostDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdatePostDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'content': json['content'],
        'contentType': json['contentType'],
    };
}

export function UpdatePostDTOToJSON(value?: UpdatePostDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'content': value.content,
        'contentType': value.contentType,
    };
}

