/* tslint:disable */
/* eslint-disable */
/**
 * Chat - API
 * Chat - API Description
 *
 * The version of the OpenAPI document: 1.1.60
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserResponseDTO
 */
export interface UserResponseDTO {
    /**
     * 
     * @type {number}
     * @memberof UserResponseDTO
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof UserResponseDTO
     */
    username: string;
}

/**
 * Check if a given object implements the UserResponseDTO interface.
 */
export function instanceOfUserResponseDTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "username" in value;

    return isInstance;
}

export function UserResponseDTOFromJSON(json: any): UserResponseDTO {
    return UserResponseDTOFromJSONTyped(json, false);
}

export function UserResponseDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserResponseDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'username': json['username'],
    };
}

export function UserResponseDTOToJSON(value?: UserResponseDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'username': value.username,
    };
}

